<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FonctionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('fonctions')->insert([
            ['intitule' => "Acheteur - Démarcheur"],
            ['intitule' => "Adjoint Chef De Carrière"],
            ['intitule' => "Administratrice"],
            ['intitule' => "Agent Commercial"],
            ['intitule' => "Agent De Bureau"],
            ['intitule' => "Agent De Contrôl De Sortie"],
            ['intitule' => "Agent De Contrôl D'entrée"],
            ['intitule' => "Agent De Contrôl Qualité Et Exploitation"],
            ['intitule' => "Agent De Controle Entree/Sortie"],
            ['intitule' => "Agent De Sécurité"],
            ['intitule' => "Agent D'expedition N1"],
            ['intitule' => "Agent Polyvalent"],
            ['intitule' => "Aide Comptable"],
            ['intitule' => "Aide Laborantin Niveau 02"],
            ['intitule' => "Aide Magasinier"],
            ['intitule' => "Aide Mécanicien"],
            ['intitule' => "Aide Menuisier"],
            ['intitule' => "Apprentis"],
            ['intitule' => "Assistante De Direction"],
            ['intitule' => "Assistante Ressources Humaines"],
            ['intitule' => "Auditeur Interne"],
            ['intitule' => "Caissier Niveau 01"],
            ['intitule' => "Caissier Principal"],
            ['intitule' => "Ch. De  Serv  G.R.H"],
            ['intitule' => "Ch.Bureau Commercia."],
            ['intitule' => "Ch.Equip.Securite"],
            ['intitule' => "Ch.Serv.Moyene Gener Et Logistique"],
            ['intitule' => "Chargé De Suivi"],
            ['intitule' => "Chau Tracteur"],
            ['intitule' => "Chauffeur Camion Malaxeur"],
            ['intitule' => "Chauffeur Poid Léger"],
            ['intitule' => "Chauffeur Poids Lourd"],
            ['intitule' => "Chauffeur Semi Remorque N1"],
            ['intitule' => "Chauffeur Véhicule Leger N1"],
            ['intitule' => "Chef  De  Projet"],
            ['intitule' => "Chef .Serv.Finance"],
            ['intitule' => "Chef De  Projet Polyvalent Ppl"],
            ['intitule' => "Chef De Carrière"],
            ['intitule' => "Chef De Chantier"],
            ['intitule' => "Chef De Département Finances & Comptabilité"],
            ['intitule' => "Chef De Groupe Prevention Et Securite"],
            ['intitule' => "Chef De Parc"],
            ['intitule' => "Chef De Poste C.Sort"],
            ['intitule' => "Chef De Poste Controle Entree / Sortie"],
            ['intitule' => "Chef De Service Comptabilite Et Finance"],
            ['intitule' => "Chef De Service Maintenance"],
            ['intitule' => "Chef Département Des Batîments"],
            ['intitule' => "Chef Département Logistique & Moyens Généraux"],
            ['intitule' => "Chef Departement Rh Et Moyen Genereau"],
            ['intitule' => "Chef Departement Rh/Moyens"],
            ['intitule' => "Chef Département Technique Et Développement"],
            ['intitule' => "Chef Departement Technique Et Exploitation"],
            ['intitule' => "Chef D'equipe"],
            ['intitule' => "Chef D'equipe Des Ferrailleurs"],
            ['intitule' => "Chef d'Equipe Des Maçons"],
            ['intitule' => "Chef D'equipe Des Menuisiers"],
            ['intitule' => "Chef D'unite"],
            ['intitule' => "Chef Serv Vend"],
            ['intitule' => "Chef Service Approvisionnement Gestion Des Stocks"],
            ['intitule' => "Chef Service Commercial"],
            ['intitule' => "Chef Service De Comptabilité"],
            ['intitule' => "Chef Service Finance Et Comptabilite"],
            ['intitule' => "Chef Service Hse"],
            ['intitule' => "Chef Service Production Et Maintenance"],
            ['intitule' => "Chef. Serv.Tech.Commercail"],
            ['intitule' => "Coffreur"],
            ['intitule' => "Comptable Annalytique"],
            ['intitule' => "Comptable Niveau 02"],
            ['intitule' => "Comptable Principal"],
            ['intitule' => "Conducteur Chariot Elevateur Niveau 02"],
            ['intitule' => "Conducteur De Travaux"],
            ['intitule' => "Conducteur D'engins"],
            ['intitule' => "Contremaitre Atelier"],
            ['intitule' => "Contrôleur De Gestion"],
            ['intitule' => "Departement Finance Et Comptabilite"],
            ['intitule' => "Directeur"],
            ['intitule' => "Directeur D'unite"],
            ['intitule' => "Directeur Régional"],
            ['intitule' => "Electricien De Batiments"],
            ['intitule' => "Fact .Caissier"],
            ['intitule' => "Facturier"],
            ['intitule' => "Femme Charge"],
            ['intitule' => "Femme De Menage N1"],
            ['intitule' => "Ferra. 2eme Degre"],
            ['intitule' => "Ferra. 3eme Degre"],
            ['intitule' => "Ferrailleur 1°"],
            ['intitule' => "Gardien"],
            ['intitule' => "Gardien De Nuit"],
            ['intitule' => "Gardien De Nuit"],
            ['intitule' => "Gestionnair.Stock"],
            ['intitule' => "Gestionnaire Stockes N1"],
            ['intitule' => "Ingenieur  Etat Hydrogeologie"],
            ['intitule' => "Ingenieur Etat Geni"],
            ['intitule' => "Ingenieur Genie Civile"],
            ['intitule' => "Ingénieur Suivi De Projet"],
            ['intitule' => "Maçon 01°"],
            ['intitule' => "Maçon 02°"],
            ['intitule' => "Maçon 03°"],
            ['intitule' => "Magasiner N1"],
            ['intitule' => "Magasinier"],
            ['intitule' => "Manoeuvre"],
            ['intitule' => "Manoeuvre Commun N1"],
            ['intitule' => "Mecanicien Auto Essence"],
            ['intitule' => "Mecanicien Engin"],
            ['intitule' => "Mecanicien Industriel Niveau 01"],
            ['intitule' => "Menuisier"],
            ['intitule' => "Operateur"],
            ['intitule' => "Operateur"],
            ['intitule' => "Opérateur Centrale À Béton"],
            ['intitule' => "Opérateur De Grue"],
            ['intitule' => "Opérateur De Pompe"],
            ['intitule' => "Opérateur Polyvalent"],
            ['intitule' => "Operatrice  En  Informatique"],
            ['intitule' => "Ouvrier Specialise N1"],
            ['intitule' => "Peintre"],
            ['intitule' => "Plombier"],
            ['intitule' => "Pointeur"],
            ['intitule' => "Responsable   H.S.E  Et  S.I.E"],
            ['intitule' => "Responsable  Commercial"],
            ['intitule' => "Responsable Approvisionnement"],
            ['intitule' => "Responsable Cellule Commercial"],
            ['intitule' => "Responsable Cellule Parque Et Maintenance"],
            ['intitule' => "Responsable Prevention Et Securite"],
            ['intitule' => "Secretaire"],
            ['intitule' => "Secretaire De Direct"],
            ['intitule' => "Secretaire De Direction Niveau 01"],
            ['intitule' => "Secretaire Direction Niv2"],
            ['intitule' => "Soudeur"],
            ['intitule' => "Soudeur 1er Degre"],
            ['intitule' => "Soudeur 3er Degre"],
            ['intitule' => "Superviseur Hse Niveau 01"],
            ['intitule' => "Tech. En Comptabilite"],
            ['intitule' => "Tech. Informatique"],
            ['intitule' => "Tech. Supr.De Maintenance De Systemes Informatiques"],
            ['intitule' => "Tech.Supr.Informat."],
            ['intitule' => "Tolier"],
            ['intitule' => "Tourneur"],
            ['intitule' => "Vulganisateur"],
        ]);
    }
}
